In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [54]:
df = pd.read_csv('data/train.csv')
df

,id,user_address,user_balance_usd,user_balance_coin_a,user_historical_transactions_10s,user_historical_transactions_30s,exchange_a_price,exchange_b_price,exchange_a_volatility,exchange_b_volatility,anonymous,result
0,8,0x930B,84139.092267,44.193560,0,0,66.742521,66.8325,very high,0.000367,A113,0
1,12,0x5779,34609.449276,331.501171,0,0,41.429574,41.5401,low,0.000695,M958,0
2,28,0x5779,30598.783296,1581.902691,0,0,35.817631,35.8701,very low,0.000431,F255,0
3,50,0x5779,20992.680359,1260.406181,0,0,47.711827,47.8233,low,0.000456,F2332,0
4,56,0xD47A,120838.946555,180.090128,0,0,52.812842,52.6869,low,NaN,A198,0
...,...,...,...,...,...,...,...,...,...,...,...,...
338482,3988947,0x5779,29374.263175,352.561329,0,0,46.680615,46.6683,medium,0.000435,M142,0
338483,3988948,0x5AEe,50847.577759,239.577796,0,0,72.139667,360.4125,low,0.000452,A131,0
338484,3988961,0x930B,121303.381921,160.222687,0,0,52.285416,52.3887,low,0.000285,A2158,0
338485,3988964,0x5779,18515.028195,1927.485662,0,0,38.559282,38.6211,very low,0.000185,F1831,0
338486,3988973,0x5779,21459.884902,526.017633,0,0,NaN,47.0295,low,0.000437,M1012,0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338487 entries, 0 to 338486
Data columns (total 12 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id                                338487 non-null  int64
 1   user_address                      338487 non-null  object
 2   user_balance_usd                  338487 non-null  float64
 3   user_balance_coin_a               338487 non-null  float64
 4   user_historical_transactions_10s  338487 non-null  int64
 5   user_historical_transactions_30s  338487 non-null  int64
 6   exchange_a_price                  309845 non-null  float64
 7   exchange_b_price                  338487 non-null  float64
 8   exchange_a_volatility             323277 non-null  object
 9   exchange_b_volatility             330565 non-null  float64
 10  anonymous                         338487 non-null  object
 11  result                            338487 non-null  int64
dtypes: float64(5), int64(4), object(3)
memory usage: 31.0+ MB

In [56]:
df_test = df.copy()
df_test = df_test.dropna()
df_test['price_diff'] = df_test['exchange_a_price'] - df_test['exchange_b_price']
df_test = df_test.drop(columns=['id', 'user_address', 'anonymous', 'exchange_a_volatility', 'exchange_b_volatility'], axis=1)
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 289060 entries, 0 to 338485
Data columns (total 8 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   user_balance_usd                  289060 non-null  float64
 1   user_balance_coin_a               289060 non-null  float64
 2   user_historical_transactions_10s  289060 non-null  int64
 3   user_historical_transactions_30s  289060 non-null  int64
 4   exchange_a_price                  289060 non-null  float64
 5   exchange_b_price                  289060 non-null  float64
 6   result                            289060 non-null  int64
 7   price_diff                        289060 non-null  float64
dtypes: float64(5), int64(3)
memory usage: 19.8 MB

In [52]:
# df_test['user_historical_transactions_30s'].value_counts()
# df_test[df_test['user_historical_transactions_30s'] == 2]['result'].value_counts()
# df_test['exchange_b_volatility'].describe()

count    289060.000000
mean          0.000459
std           0.000334
min           0.000000
25%           0.000248
50%           0.000375
75%           0.000570
max           0.010446
Name: exchange_b_volatility, dtype: float64

In [50]:
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
# encoder = OneHotEncoder()
# encoder_df = pd.DataFrame(encoder.fit_transform(df_test[['exchange_a_volatility']]).toarray())
dummies = pd.get_dummies(df_test['exchange_a_volatility'], prefix='exchange_a_volatility', prefix_sep='_')
#merge one-hot encoded columns back with original DataFrame
df_test = df_test.join(dummies)
df_test = df_test.drop(columns='exchange_a_volatility', axis=1)

,user_balance_usd,user_balance_coin_a,user_historical_transactions_10s,user_historical_transactions_30s,exchange_a_price,exchange_b_price,exchange_a_volatility,exchange_b_volatility,result,price_diff,exchange_a_volatility_high,exchange_a_volatility_low,exchange_a_volatility_medium,exchange_a_volatility_very high,exchange_a_volatility_very low
0,84139.092267,44.193560,0,0,66.742521,66.8325,very high,0.000367,0,-0.089979,0,0,0,1,0
1,34609.449276,331.501171,0,0,41.429574,41.5401,low,0.000695,0,-0.110526,0,1,0,0,0
2,30598.783296,1581.902691,0,0,35.817631,35.8701,very low,0.000431,0,-0.052469,0,0,0,0,1
3,20992.680359,1260.406181,0,0,47.711827,47.8233,low,0.000456,0,-0.111473,0,1,0,0,0
5,46749.264981,272.167309,0,0,68.627842,68.6049,low,0.000188,0,0.022942,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338481,72909.885451,352.813282,0,0,66.309526,66.1437,low,0.000158,0,0.165826,0,1,0,0,0
338482,29374.263175,352.561329,0,0,46.680615,46.6683,medium,0.000435,0,0.012315,0,0,1,0,0
338483,50847.577759,239.577796,0,0,72.139667,360.4125,low,0.000452,0,-288.272833,0,1,0,0,0
338484,121303.381921,160.222687,0,0,52.285416,52.3887,low,0.000285,0,-0.103284,0,1,0,0,0
338485,18515.028195,1927.485662,0,0,38.559282,38.6211,very low,0.000185,0,-0.061818,0,0,0,0,1

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, plot_confusion_matrix, roc_auc_score, roc_curve

X = df_test.drop(columns='result', axis=1)
y = df_test['result']
scaler = StandardScaler()
X[list(X.columns)] = scaler.fit_transform(X)
# list(X.columns)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
lr = LogisticRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))
print(roc_auc_score(y_test, pred))
# roc_curve(y_test, pred)
X
# plot_confusion_matrix(lr, X_test, y_test)

              precision    recall  f1-score   support

           0       0.95      0.99      0.97     80697
           1       0.71      0.23      0.35      6021

    accuracy                           0.94     86718
   macro avg       0.83      0.61      0.66     86718
weighted avg       0.93      0.94      0.93     86718

[[80135   562]
 [ 4620  1401]]
0.6128606385328216

,user_balance_usd,user_balance_coin_a,user_historical_transactions_10s,user_historical_transactions_30s,exchange_a_price,exchange_b_price,price_diff
0,0.645185,-0.962203,-0.111438,-0.226856,1.106540,0.214967,0.164978
1,-1.030018,-0.353800,-0.111438,-0.226856,-0.966160,-0.474437,0.164376
2,-1.165667,2.294052,-0.111438,-0.226856,-1.425683,-0.628986,0.166078
3,-1.490567,1.613251,-0.111438,-0.226856,-0.451750,-0.303173,0.164348
5,-0.619422,-0.479445,-0.111438,-0.226856,1.260916,0.263278,0.168289
...,...,...,...,...,...,...,...
338481,0.265389,-0.308669,-0.111438,-0.226856,1.071085,0.196192,0.172478
338482,-1.207083,-0.309203,-0.111438,-0.226856,-0.536189,-0.334656,0.167977
338483,-0.480808,-0.548457,-0.111438,-0.226856,1.548475,8.217175,-8.284111
338484,1.902164,-0.716500,-0.111438,-0.226856,-0.077251,-0.178733,0.164588
338485,-1.574367,3.025859,-0.111438,-0.226856,-1.201189,-0.554001,0.165804